name: redditech
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get_it: ^7.1.3
  provider: ^5.0.0
  test: ^1.16.8
  dio: ^4.0.0
  firebase: ^9.0.1
  firebase_core: ^1.3.0
  cloud_firestore: ^2.2.2
  firebase_storage: ^8.1.3
  firebase_auth: ^1.4.1
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  json_annotation: ^4.0.1
  flutter_dotenv: ^5.0.2
  webview_flutter: ^2.1.2
  gap: ^2.0.0
  flutter_svg: ^0.23.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.1
  json_serializable: ^4.1.3
  hive_generator: ^1.1.0
  flutter_lints: ^1.0.3

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/png/
    - assets/fonts/
    - .env
  fonts:
    - family: Poppins
      fonts:
      - asset: assets/fonts/Poppins-Regular.ttf
      - asset: assets/fonts/Poppins-Italic.ttf
        style: italic
      - asset: assets/fonts/Poppins-ExtraLight.ttf
        weight: 100
      - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
        weight: 100
        style: italic
      - asset: assets/fonts/Poppins-Thin.ttf
        weight: 200
      - asset: assets/fonts/Poppins-ThinItalic.ttf
        weight: 200
        style: italic
      - asset: assets/fonts/Poppins-Medium.ttf
        weight: 300
      - asset: assets/fonts/Poppins-MediumItalic.ttf
        weight: 300
        style: italic
      - asset: assets/fonts/Poppins-SemiBold.ttf
        weight: 400
      - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
        weight: 400
        style: italic
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 600
      - asset: assets/fonts/Poppins-BoldItalic.ttf
        weight: 600
        style: italic
      - asset: assets/fonts/Poppins-ExtraBold.ttf
        weight: 700
      - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
        weight: 700
        style: italic

